### ISSUE TITLE
mod fails to load correctly on dedicated server

### ISSUE THREAD

**Issue by N00b14nL00z3r** [wutdahack/ActuallyUnbreakingForge#1]
it works fine in multimc but not the server
[latest.log](https://github.com/wutdahack/ActuallyUnbreakingForge/files/13760867/latest.log)

**Comment by wutdahack** [comment]
can you tell me what mods you're playing with?

**Comment by N00b14nL00z3r** [comment]
here is the crash report
[crash-2023-12-22_19.44.04-fml.txt](https://github.com/wutdahack/ActuallyUnbreakingForge/files/13803851/crash-2023-12-22_19.44.04-fml.txt)

this is just the modlist
[modlist.txt](https://github.com/wutdahack/ActuallyUnbreakingForge/files/13803855/modlist.txt)

**Comment by wutdahack** [comment]
thank you! does this fix the crash?
[actuallyunbreaking-1.20.1-0.1.1.zip](https://github.com/wutdahack/ActuallyUnbreakingForge/files/13809969/actuallyunbreaking-1.20.1-0.1.1.zip)

**Comment by N00b14nL00z3r** [comment]
yes it does
