### ISSUE TITLE
Can't launch on ded. server 1.19.2.

### ISSUE THREAD

**Issue by Korolev3377** [wutdahack/ActuallyUnbreakingForge#2]
Like in issue on 1.20, but on 1.19.2
[crash-2024-01-11_18.38.45-fml.txt](https://github.com/wutdahack/ActuallyUnbreakingForge/files/13904770/crash-2024-01-11_18.38.45-fml.txt)

**Comment by Korolev3377** [comment]
Uh-oh. I didn't realize there was a version 1.1 here.
There's only version 1.0 on CurseForge.
1.1 Works fine/

**Comment by wutdahack** [comment]
version 0.1.1 should be uploaded to curseforge
