### ISSUE TITLE
Adding Ukrainian Translation

### ISSUE THREAD

**Issue by SadSvita** [wutdahack/ActuallyUnbreakingForge#3]
hello i was wondering if you would like me to translate the mod to ukrainian for you

**Comment by wutdahack** [comment]
sure if you want to! :)

**Comment by SadSvita** [comment]
question is mending\nif and the others like that a typo or does it mean something?

**Comment by wutdahack** [comment]
the "\n" adds a new line

**Comment by SadSvita** [comment]
ok so it would just mean if and the same for the rest

**Comment by SadSvita** [comment]
unbreakable\nnbt would be what then...sorry for all the questions i just want to make sure its right

**Comment by wutdahack** [comment]
yeah but you'll still need to add the "\n" between the words

**Comment by SadSvita** [comment]
{
"text.config.actuallyunbreaking.title": "Фактично непорушна конфігурація",

"text.config.actuallyunbreaking.option.maxLevelOnly": "лише максимальний рівень",
"text.config.actuallyunbreaking.option.useUnbreakableAtLevel": "використовуйте непорушний на рівні номер",
"text.config.actuallyunbreaking.option.unbreakableAtLevel": "непорушний на рівні",
"text.config.actuallyunbreaking.option.mendingIncompatibility": "несумісний з ремонтом",
"text.config.actuallyunbreaking.option.useUnbreakableTag": "використовуйте незламний тег",

"text.config.actuallyunbreaking.comment.maxLevelOnly": "лише останній рівень непорушності встановить інструмент/nяк непорушний, якщо це правда.",
"text.config.actuallyunbreaking.comment.useUnbreakableAtLevel": "якщо це правда, інструмент буде\nнезламним лише на визначеному рівні\n(перевизначає параметр максимального рівня).",
"text.config.actuallyunbreaking.comment.unbreakableAtLevel": "якщо це правда, інструмент буде\nнезламним лише на визначеному рівні\n(перевизначає параметр максимального рівня).",
"text.config.actuallyunbreaking.comment.mendingIncompatibility": "непорушний буде несумісним із ремонтом\nякщо це правда.",
"text.config.actuallyunbreaking.comment.useUnbreakableTag": "коли інструмент отримує пошкодження, тег непорушний\nnbt буде додано, а непорушний (і ремонт) буде\nвидалено з інструменту (ви більше не зможете\nдодати непорушний і ремонт до інструменту), якщо це правда."
}

**Comment by wutdahack** [comment]
it's okay and thanks so much for the translation! i'll add it to the mod later as i'm currently busy

**Comment by SadSvita** [comment]
Of course no problem
